In [2]:
import pandas as pd
data = pd.read_csv("Sales Data.csv")  
data.head()

,TransactionID,ProductID,ProductName,ProductCategory,SalesQuantity,SalesPrice,DiscountAmount,FinalSalePrice,TransactionDate,TimeOfDay,...,StoreLocation,Region,PromoCodeUsed,DiscountPercentage,ShippingMethod,ShippingFee,ShippingStatus,SalesTax,CrossSellProducts,UpsellProducts
0,TX833547,1073,Product_1073,Furniture,7,232,42.990911,189.009089,2024-12-05,Evening,...,Store_12,South,False,0.000000,Expedited,5,In-transit,18.900909,Product_1014,NaN
1,TX623643,1086,Product_1086,Furniture,7,177,21.299548,155.700452,2025-01-29,Afternoon,...,Store_34,South,True,5.085918,Standard,18,Delivered,15.570045,NaN,Product_1510
2,TX248379,1063,Product_1063,Clothing,3,475,35.980273,439.019727,2024-11-03,Evening,...,Store_34,West,True,2.720640,Standard,7,Pending,43.901973,Product_1037,Product_1548
3,TX444636,1058,Product_1058,Electronics,8,113,15.838799,97.161201,2025-01-26,Morning,...,Store_38,North,True,17.608179,None,0,In-transit,9.716120,Product_1027,NaN
4,TX900487,1086,Product_1086,Furniture,2,210,40.013375,169.986625,2024-11-12,Morning,...,Store_36,South,False,0.000000,None,0,Delivered,16.998663,Product_1085,NaN

In [3]:
data.isnull().sum()

TransactionID               0
ProductID                   0
ProductName                 0
ProductCategory             0
SalesQuantity               0
SalesPrice                  0
DiscountAmount              0
FinalSalePrice              0
TransactionDate             0
TimeOfDay                   0
SalesChannel                0
PaymentMethod               0
PaymentStatus               0
TransactionStatus           0
CustomerID                  0
CustomerAge                 0
CustomerGender              0
CustomerLocation            0
LoyaltyProgramMember        0
CustomerFeedbackRating      0
ReturnFlag                  0
ReturnReason              254
StoreLocation               0
Region                      0
PromoCodeUsed               0
DiscountPercentage          0
ShippingMethod              0
ShippingFee                 0
ShippingStatus              0
SalesTax                    0
CrossSellProducts         466
UpsellProducts            488
dtype: int64

In [104]:
# Step 4: Fill the null values in the specified columns with 'unknown'
df['ReturnReason'] = df['ReturnReason'].fillna('NOT pROVIDED')
df['CrossSellProducts'] = df['CrossSellProducts'].fillna('no')
df['UpsellProducts'] = df['UpsellProducts'].fillna('unknown')

In [105]:
df.isnull().sum()

TransactionID             0
ProductID                 0
ProductName               0
ProductCategory           0
SalesQuantity             0
SalesPrice                0
DiscountAmount            0
FinalSalePrice            0
TransactionDate           0
TimeOfDay                 0
SalesChannel              0
PaymentMethod             0
PaymentStatus             0
TransactionStatus         0
CustomerID                0
CustomerAge               0
CustomerGender            0
CustomerLocation          0
LoyaltyProgramMember      0
CustomerFeedbackRating    0
ReturnFlag                0
ReturnReason              0
StoreLocation             0
Region                    0
PromoCodeUsed             0
DiscountPercentage        0
ShippingMethod            0
ShippingFee               0
ShippingStatus            0
SalesTax                  0
CrossSellProducts         0
UpsellProducts            0
dtype: int64

In [106]:
# Step 5: Check for duplicates in the main data
duplicates = df.duplicated(subset=df.columns).sum()
print(f"Total Duplicates: {duplicates}")

Total Duplicates: 0

In [107]:
# 2. Check for Duplicates (No deletion, add surrogate key if needed)
df["SurrogateID"] = range(1, len(df) + 1)  # Unique identifier

In [108]:
# 3. Create Dimension Tables with Surrogate Keys

# Customer Dimension Table
dim_customer = df[[
    "CustomerID", "CustomerAge", "CustomerGender", "CustomerLocation", 
    "LoyaltyProgramMember", "CustomerFeedbackRating"
]].drop_duplicates().reset_index(drop=True)
dim_customer["CustomerKey"] = dim_customer.index + 1  # Surrogate Key

# Product Dimension Table
dim_product = df[[
    "ProductID", "ProductName", "ProductCategory"
]].drop_duplicates().reset_index(drop=True)
dim_product["ProductKey"] = dim_product.index + 1  # Surrogate Key

# Store Dimension Table
dim_store = df[[
    "StoreLocation", "Region"
]].drop_duplicates().reset_index(drop=True)
dim_store["StoreKey"] = dim_store.index + 1  # Surrogate Key

# Shipping Dimension Table
dim_shipping = df[[
    "ShippingMethod", "ShippingFee", "ShippingStatus"
]].drop_duplicates().reset_index(drop=True)
dim_shipping["ShippingKey"] = dim_shipping.index + 1  # Surrogate Key

# Promotion Dimension Table
dim_promotion = df[[
    "PromoCodeUsed", "DiscountPercentage"
]].drop_duplicates().reset_index(drop=True)
dim_promotion["PromotionKey"] = dim_promotion.index + 1  # Surrogate Key

# Sales Strategy Dimension Table (For Cross-Sell & Up-Sell)
dim_sales_strategy = df[[
    "CrossSellProducts", "UpsellProducts"
]].drop_duplicates().reset_index(drop=True)
dim_sales_strategy["SalesStrategyKey"] = dim_sales_strategy.index + 1  # Surrogate Key

# Transaction Details Dimension Table
dim_transaction_details = df[[
    "TimeOfDay", "SalesChannel", "PaymentMethod", "PaymentStatus", "TransactionStatus", "ReturnFlag", "ReturnReason"
]].drop_duplicates().reset_index(drop=True)
dim_transaction_details["TransactionDetailKey"] = dim_transaction_details.index + 1  # Surrogate Key

# 4. Merge Surrogate Keys into Fact Table
fact_sales = df.merge(dim_customer, on=["CustomerID", "CustomerAge", "CustomerGender", "CustomerLocation", 
                                        "LoyaltyProgramMember", "CustomerFeedbackRating"], how="left")

fact_sales = fact_sales.merge(dim_product, on=["ProductID", "ProductName", "ProductCategory"], how="left")
fact_sales = fact_sales.merge(dim_store, on=["StoreLocation", "Region"], how="left")
fact_sales = fact_sales.merge(dim_shipping, on=["ShippingMethod", "ShippingFee", "ShippingStatus"], how="left")
fact_sales = fact_sales.merge(dim_promotion, on=["PromoCodeUsed", "DiscountPercentage"], how="left")
fact_sales = fact_sales.merge(dim_sales_strategy, on=["CrossSellProducts", "UpsellProducts"], how="left")
fact_sales = fact_sales.merge(dim_transaction_details, on=["TimeOfDay", "SalesChannel", "PaymentMethod", "PaymentStatus", 
                                                           "TransactionStatus", "ReturnFlag", "ReturnReason"], how="left")

# Select only relevant columns for fact table (only numerical attributes)
fact_sales = fact_sales[[
    "SurrogateID", "TransactionID", "CustomerKey", "ProductKey", "StoreKey", "ShippingKey", "PromotionKey", "SalesStrategyKey", "TransactionDetailKey",
    "SalesQuantity", "SalesPrice", "DiscountAmount", "FinalSalePrice", "TransactionDate", "SalesTax"
]]

In [109]:
# 5. Save All Tables as CSV for Power BI
dim_customer.to_csv(r"C:\Users\Harishkanna.u\OneDrive - Mu Sigma Business Solutions Pvt. Ltd\Desktop\dim_customer.csv", index=False)
dim_product.to_csv(r"C:\Users\Harishkanna.u\OneDrive - Mu Sigma Business Solutions Pvt. Ltd\Desktop\dim_product.csv", index=False)
dim_store.to_csv(r"C:\Users\Harishkanna.u\OneDrive - Mu Sigma Business Solutions Pvt. Ltd\Desktop\dim_store.csv", index=False)
dim_shipping.to_csv(r"C:\Users\Harishkanna.u\OneDrive - Mu Sigma Business Solutions Pvt. Ltd\Desktop\dim_shipping.csv", index=False)
dim_promotion.to_csv(r"C:\Users\Harishkanna.u\OneDrive - Mu Sigma Business Solutions Pvt. Ltd\Desktop\dim_promotion.csv", index=False)
fact_sales.to_csv(r"C:\Users\Harishkanna.u\OneDrive - Mu Sigma Business Solutions Pvt. Ltd\Desktop\fact_sales.csv", index=False)

print("All tables saved successfully for Power BI modeling!")

All tables saved successfully for Power BI modeling!